// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcTyDq4Da_ywtRTUQ86-fpyUzXI2jqx0',
    appId: '1:48349628113:web:94ef21776ab986423aa7f0',
    messagingSenderId: '48349628113',
    projectId: 'ecommerce-f8d1f',
    authDomain: 'ecommerce-f8d1f.firebaseapp.com',
    storageBucket: 'ecommerce-f8d1f.appspot.com',
    measurementId: 'G-7JN5S1PL9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZcF4ZKZtIKUNbeLftojnRTP_CX9r8bo',
    appId: '1:48349628113:android:b16ced710bcded2a3aa7f0',
    messagingSenderId: '48349628113',
    projectId: 'ecommerce-f8d1f',
    storageBucket: 'ecommerce-f8d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWUmgzFQBaoZ9PCATT2y_O8XWxMs5ZUU',
    appId: '1:48349628113:ios:4341d4ef4cca480a3aa7f0',
    messagingSenderId: '48349628113',
    projectId: 'ecommerce-f8d1f',
    storageBucket: 'ecommerce-f8d1f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWUmgzFQBaoZ9PCATT2y_O8XWxMs5ZUU',
    appId: '1:48349628113:ios:4341d4ef4cca480a3aa7f0',
    messagingSenderId: '48349628113',
    projectId: 'ecommerce-f8d1f',
    storageBucket: 'ecommerce-f8d1f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKcTyDq4Da_ywtRTUQ86-fpyUzXI2jqx0',
    appId: '1:48349628113:web:f88bc1f0fee2f54e3aa7f0',
    messagingSenderId: '48349628113',
    projectId: 'ecommerce-f8d1f',
    authDomain: 'ecommerce-f8d1f.firebaseapp.com',
    storageBucket: 'ecommerce-f8d1f.appspot.com',
    measurementId: 'G-5KQ0PZB1ZR',
  );
}
